### ISSUE TITLE
Clarify CSN013's completion status

### ISSUE THREAD

**Issue by psokolhessner** [sokolhessnerlab/itrackvalr#15]
CSN013 has data missing (identified during issue #5) - specifically eye-tracking data is missing, while all questionnaires & other info is present. Checklist identifies no reason they were discarded, neither does recruitment Google Spreadsheet.

- [x] Either locate CSN013's eye-tracking data or clarify why their eye-tracking data is missing.

**Comment by psokolhessner** [comment]
CSN013's eye-tracking data was present on the collection computers, and simply hadn't been backed up. 

All 4 missing data files (eye-tracking EDF, eye-tracking MAT, behavioral data MAT, tmp behavioral data TXT) have been uploaded to the S drive.

**Comment by aridyckovsky** [comment]
Fantastic will work those new files into the pre-processing phase. Thanks @psokolhessner
