### ISSUE TITLE
Age and gender completions in CSV

### ISSUE THREAD

**Issue by aridyckovsky** [sokolhessnerlab/itrackvalr#22]
**Problem**

Age and gender completions needed in `data/raw/questionnaire/CSN_agegender.csv` on S Drive.

**Solution**

The following items should be included within the CSV for completion:

- The first column has rows for the participant's unique string id (i.e., CSN001).
- Every participant through CSN057 should have an **age** and **gender** entry.

**Comment by aridyckovsky** [comment]
FWIW @psokolhessner this could be a good first issue as reflected by labels

**Comment by psokolhessner** [comment]
Note that because of occasional missing data, there may be some sleuthing/following-up necessary with individual participants.

**Comment by psokolhessner** [comment]
This is a test comment.

**Comment by psokolhessner** [comment]
We have sex information for all but 2 participants (both of whom did not complete the study). Analyses should be able to leverage all participants' sex. 

We have age information for all but 7 participants (4 of whom did not complete the study). Analyses will be missing 3 participants' ages.
