### ISSUE TITLE
Summarize participants with incomplete task data

### ISSUE THREAD

**Issue by aridyckovsky** [sokolhessnerlab/itrackvalr#5]
# Summarize participants with incomplete task data

## Questions to answer

- [x] How many participants were incomplete?
- [x] What were the reasons participants did not complete the task?
- [x] Can we group the incompletes by common reasons?

## Additional context

See CSN participant recruitment spreadsheet in the S Drive for individual reasons.

**Comment by aridyckovsky** [comment]
Having some issues determining whether CSN013 completed the task. The checklist for that participant says the session **was** completed. However, the data check you performed previously in MATLAB comments out that participant: https://github.com/sokolhessnerlab/itrackvalr/blob/main/matlab/csn_datacheck_03.m#L23. Any ideas? My assumption is that the checklist is correct, but want to be sure.

**Comment by aridyckovsky** [comment]
I've pushed a first draft of the summary responses. At this time, we are lacking notes on _why_ CSN031 did not complete, and we are also awaiting confirmation that CSN013 did (or did not) complete the task.

**Comment by psokolhessner** [comment]
Re: CSN013, that's a great question. I see no eye-tracking for them, but no other indication that there was an error or other issue. I'll follow up on the eyetracking computer itself. 

Will set up separate issue to either locate CSN013's data or clarify why their eye-tracking data is missing.

**Comment by psokolhessner** [comment]
Separately, CSN031 "Could not complete study due to poor calibration (glasses)" (from recruitment Google Spreadsheet).
